version: "3.9"  # optional since v1.27.0
services:
  cookbook:
    build: .
    entrypoint: pytest test
    depends_on:
      - dynamo
  dynamo:
    image: amazon/dynamodb-local
    ports:
    - 8000:8000
volumes:
  logvolume01: {}